### PR TITLE
Don't try to parse files that don't exist

### LINKED ISSUE #1337: FileNotFoundException when running running buildHealth after deleting a file
**Plugin version**
2.6.0

**Gradle version**
8.11.1

**JDK version**
22

**(Optional) Kotlin and Kotlin Gradle Plugin (KGP) version**
2.1.0

**(Optional) Android Gradle Plugin (AGP) version**
8.7.3

**Describe the bug**
If I run `buildHealth`, then delete a file, then run `buildHealth` again, I get a `FileNotFoundException`. If I run `buildHealth --no-configuration-cache` then it succeeds (but running again without `--no-configuration-cache` continues to fail until presumably the configuration cache is invalidated).

```
java.io.FileNotFoundException: /home/eli/workspace/my-app/library/src/main/kotlin/com/myapp/DeviceType.kt (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
        at com.autonomousapps.internal.parse.SourceListener$Companion.newSimpleParser(SourceListener.kt:39)
        at com.autonomousapps.internal.parse.SourceListener$Companion.parseSourceFileForImports(SourceListener.kt:33)
        at com.autonomousapps.tasks.SourceExploder.explode(CodeSourceExploderTask.kt:119)
        at com.autonomousapps.tasks.CodeSourceExploderTask$CodeSourceExploderWorkAction.execute(CodeSourceExploderTask.kt:87)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:62)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:100)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:62)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:59)
        at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$0(DefaultWorkerExecutor.java:174)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:194)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.access$700(DefaultConditionalExecutionQueue.java:127)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner$1.run(DefaultConditionalExecutionQueue.java:169)
        at org.gradle.internal.Factories$1.create(Factories.java:31)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:263)
        at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:127)
        at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:132)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:133)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        ... 5 more
```

### PR DESCRIPTION
**Pull request by eygraber**
Fixes #1337 

I would think that the cache would get invalidated because of the file change, but either it doesn't, or something else is broken. In the meantime, this should stop the errors, and provide correct behavior.

### CODE REVIEW

File: src/functionalTest/groovy/com/autonomousapps/android/AndroidFileMutationSpec.groovy [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+  def "buildHealth succeeds after deleting a file (#gradleVersion AGP #agpVersion)"() {
+    given:
+    def project = new AndroidFileMutationProject(agpVersion as String)
+    gradleProject = project.gradleProject
+
+    when: 'We build the first time'
+    build(
+      gradleVersion as GradleVersion,
+      gradleProject.rootDir,
+      'buildHealth', '--configuration-cache'
```
Comment (autonomousapps) [inline src/functionalTest/groovy/com/autonomousapps/android/AndroidFileMutationSpec.groovy]: '--configuration-cache' shouldn't be necessary. All specs in this project have this set.

File: src/functionalTest/groovy/com/autonomousapps/android/AndroidFileMutationSpec.groovy [hunk 2]
```diff
@@ -0,0 +1,92 @@
...
+    )
+
+    then: 'the build health is as expected'
+    assertAbout(buildHealth())
+      .that(project.actualBuildHealth())
+      .isEquivalentIgnoringModuleAdviceAndWarnings(project.expectedDeletionBuildHealth)
+
+    and: 'the configuration cache was used'
+    assertThat(result.getOutput()).contains("Configuration cache entry reused.")
```
Comment (autonomousapps) [inline src/functionalTest/groovy/com/autonomousapps/android/AndroidFileMutationSpec.groovy]: `result.output` is better (Groovy works similarly to Kotlin in this respect).

File: src/main/kotlin/com/autonomousapps/tasks/CodeSourceExploderTask.kt
Comment (autonomousapps) [inline src/main/kotlin/com/autonomousapps/tasks/CodeSourceExploderTask.kt:1]: This is interesting. I'm confused why Gradle would give me files that don't exist.

**Review by autonomousapps — APPROVED** [review]
Thanks for the PR! I think I'll actually checkout this branch myself and debug to try to understand why we're getting non-existent files.

- [ ] Please address the comments.
